### ISSUE TITLE
Error messages when terminate minimal.launch

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#178]
When terminating `minimal.launch` without connection to robot, there is ...

```
[ERROR] [1354028802.515485673]: Kobuki : initialisation failed [/mobile_base].
[ERROR] [1354028802.515850454]:
Location : /tmp/buildd/ros-groovy-ecl-core-0.44.0/debian/ros-groovy-ecl-core/opt/ros/groovy/stacks/ecl_core/ecl_time/src/lib/sleep_pos.cpp:44
Flag     : This operation was interrupted.
Detail   : A posix signal interrupted the sleep.

[ERROR] [1354028802.516100066]: Couldn't initialise kobuki_node.
```

**Comment by bit-pirate** [comment]
That's actually no bug. It's just we print out the exception content as error. 

``` c++
        ROS_ERROR_STREAM("Kobuki : initialisation failed [" << name << "].");
        ROS_ERROR_STREAM(e.what());
```

Will change that.

**Comment by yhju** [comment]
Here is one more error messages. I think it is problem of app_manager. 

```
^C[appmaster-7] killing on exit
[app_manager-8] killing on exit
[turtlebot_laptop_battery-6] killing on exit
 [robot_pose_ekf-5] killing on exit
[mobile_base-4] killing on exit
 [diagnostic_aggregator-3] killing on exit
[zeroconf-1] killing on exit
[INFO] [WallTime: 1354347433.915384] Unregistering (/turtlebot/app_list,http://yujin-kobuki0-laptop:51716/) from master http://localhost:11312
Traceback (most recent call last):
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/core.py", line 477, in signal_shutdown
    h()
  File "/opt/ros/fuerte/stacks/multimaster_experimental/app_manager/src/app_manager/app_manager.py", line 103, in shutdown
    self._api_sync.stop()
  File "/opt/ros/fuerte/stacks/multimaster_experimental/app_manager/src/app_manager/master_sync.py", line 289, in stop
    self.foreign_manager.unsubscribe_all()
  File "/opt/ros/fuerte/stacks/multimaster_experimental/app_manager/src/app_manager/master_sync.py", line 216, in unsubscribe_all
    self.unadvertise(t,u)
  File "/opt/ros/fuerte/stacks/multimaster_experimental/app_manager/src/app_manager/master_sync.py", line 160, in unadvertise
    m.unregisterPublisher(topic,uri)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 418, in unregisterPublisher
    return self._succeed(self.handle.unregisterPublisher(self.caller_id, topic, caller_api))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by stonier** [comment]
Already patched and sent upstream - see http://github.com/turtlebot/turtlebot/issues/8
