### ISSUE TITLE
Rare socket error when starting

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#179]
There is some errorous messages like this.

```
[ INFO] [1354029086.328113458]: Kobuki : using odom_frame [odom][/mobile_base].
[ INFO] [1354029086.334168701]: Kobuki : using base_frame [base_footprint][/mobile_base].
[ INFO] [1354029086.340360896]: Kobuki : not publishing transforms (see robot_pose_ekf) [/mobile_base].
process[robot_pose_ekf-5]: started with pid [11333]
process[turtlebot_laptop_battery-6]: started with pid [11373]
process[appmaster-7]: started with pid [11374]
process[app_manager-8]: started with pid [11377]
Unhandled exception in thread started by <bound method XmlRpcNode.run of <rosgraph.xmlrpc.XmlRpcNode object at 0x17894d0>>
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 196, in run
    self._run()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 266, in _run
    self._run_init()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 215, in _run_init
    self.server = ThreadingXMLRPCServer((bind_address, port), log_requests)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosgraph/xmlrpc.py", line 96, in __init__
    SimpleXMLRPCServer.__init__(self, addr, SilenceableXMLRPCRequestHandler, log_requests)
  File "/usr/lib/python2.7/SimpleXMLRPCServer.py", line 593, in __init__
    SocketServer.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/usr/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
turtlebot_apps.installed
loading installation data for [turtlebot_apps.installed]
[INFO] [WallTime: 1354029113.319672] Starting app manager for turtlebot
[INFO] [WallTime: 1354029113.356827] Waiting for foreign master [http://localhost:11312] to come up...
[INFO] [WallTime: 1354029113.364767] Foreign master is available
[INFO] [WallTime: 1354029113.425511] Registering (/turtlebot/app_list,http://yujin-kobuki0-laptop:35000/) on master http://localhost:11312
[INFO] [WallTime: 1354029113.440198] Registering (/turtlebot/application/app_status,http://yujin-kobuki0-laptop:35000/) on master http://localhost:11312
turtlebot_apps.installed
[INFO] [WallTime: 1354029113.458034] Registering service (/turtlebot/list_apps,rosrpc://yujin-kobuki0-laptop:56475) on master http://localhost:11312
[INFO] [WallTime: 1354029113.471171] Registering service (/turtlebot/start_app,rosrpc://yujin-kobuki0-laptop:56475) on master http://localhost:11312
[INFO] [WallTime: 1354029113.485521] Registering service (/turtlebot/stop_app,rosrpc://yujin-kobuki0-laptop:56475) on master http://localhost:11312
```

**Comment by stonier** [comment]
Can't intentionally reproduce this. Just keep an eye out for it.

**Comment by bit-pirate** [comment]
Furthermore, this might be no Kobuki bug.

**Comment by stonier** [comment]
Haven't seen this for ages so closing. Reopen if necessary.
