### ISSUE TITLE
Handle serial dropouts cleanly

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#99]
```
[ERROR] [1335522013.317484261]: Kobuki : timed out waiting for the serial data stream [/mobile_base].
^C[diagnostic_aggregator-8] killing on exit
[app_manager-7] killing on exit
[appmaster-6] killing on exit
[robot_pose_ekf-5] killing on exit
[mobile_base-4] killing on exit
[robot_state_publisher-3] killing on exit
[zeroconf-2] killing on exit
[INFO] [WallTime: 1335522042.521704] Unregistering (/kobukibot/application/app_status,http://snorriwork.yujin.com:48286/) from master http://localhost:11312
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/core.py", line 459, in signal_shutdown
    h()
  File "/opt/ros/electric/stacks/multimaster_experimental/app_manager/src/app_manager/app_manager.py", line 102, in shutdown
    self._api_sync.stop()
  File "/opt/ros/electric/stacks/multimaster_experimental/app_manager/src/app_manager/master_sync.py", line 290, in stop
    self.foreign_manager.unsubscribe_all()
  File "/opt/ros/electric/stacks/multimaster_experimental/app_manager/src/app_manager/master_sync.py", line 217, in unsubscribe_all
    self.unadvertise(t,u)
  File "/opt/ros/electric/stacks/multimaster_experimental/app_manager/src/app_manager/master_sync.py", line 161, in unadvertise
    m.unregisterPublisher(topic,uri)
  File "/opt/ros/electric/stacks/ros_comm/tools/rosgraph/src/rosgraph/masterapi.py", line 402, in unregisterPublisher
    return self._succeed(self.handle.unregisterPublisher(self.caller_id, topic, caller_api))
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/xmlrpclib.py", line 1235, in request
    self.send_content(h, request_body)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1349, in send_content
    connection.endheaders()
  File "/usr/lib/python2.6/httplib.py", line 904, in endheaders
    self._send_output()
  File "/usr/lib/python2.6/httplib.py", line 776, in _send_output
    self.send(msg)
  File "/usr/lib/python2.6/httplib.py", line 735, in send
    self.connect()
  File "/usr/lib/python2.6/httplib.py", line 716, in connect
    self.timeout)
  File "/usr/lib/python2.6/socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 111] Connection refused
terminate called after throwing an instance of 'ecl::StandardException'
  what():  
Location : /opt/kobuki/ecl_core/ecl_devices/include/ecl/devices/serial_pos.hpp:407 
Flag     : A subsystem has failed mid operation.
Detail   : A low level input-output error occured (possibly beyond your control).
```

**Comment by stonier** [comment]
Ach...also app manager! See #100

**Comment by mjason3** [comment]
i also saw 'Kobuki : timed out waiting for the serial data stream [/mobile_base].' unexpectedly during the ROS nodes were running. any idea or clues how timeout can happen?
